### ISSUE TITLE
Area tag is missing mandatory attribute alt

### ISSUE THREAD

**Issue by responseinformationsdesign** [MichaelPerlbach/mmimagemap#2]
The attribute alt for the area tag should use the value for the area description used in the backend.

**Comment by MichaelPerlbach** [comment]
alt-attributes can be added via "additional parameters"

**Comment by responseinformationsdesign** [comment]
Setting a value via "additional parameters" has no effect in the frontend. Is there any special format to be taken into account?

However as the alt attribut is mandatory if href is set it should be set anyway.

> If the area element has an href attribute, then the area element represents a hyperlink. In this case, the alt attribute must be present

([https://html.spec.whatwg.org/multipage/image-maps.html#the-area-element])

**Comment by MichaelPerlbach** [comment]
If setting a value via "additional parameters" has no effect in the frontend then it's a bug and I will take a look at it. I will further think about setting the attribute automatically - but what I fear is that when it's set automatically other users will complain about not being able to set it manually - which, in the end, makes things more complicated for me. But I will think about the most simple solution.

**Comment by MichaelPerlbach** [comment]
I corrected "additional parameters" so that adding an "alt" - or any other - parameter should work.
Just download the newest version of the extension and try it out. If any further problems occur, don't hesitate to tell me. For now, I will close this issue.
